### PR TITLE
Add svg_render example

### PR DESCRIPTION
**Pull request by zen3ger**
Based on the suggestions in #215 I've made an `svg_render` example.
It renders both shapes and strokes.

I couldn't figure out how to pass stroke styles from `resvg` to `lyon`. If someone knows, I'd be happy to add that too.

### CODE REVIEW

**Comment by nical** [comment]
Nice! There are a couple of features that would be nice to add like having correct aspect ratio no matter the size of the window and automatically positioning the view to fit the document, but we can add them as followups.

Could you squash the commits? Also could you remove center.svg, test.svg is more useful for people trying out the example.

**Comment by zen3ger** [comment]
I've fixed the centerring. By this week I'll probably fix the scaling too. It took quite some time to find a [gfx example](https://gist.github.com/matthewjberger/c1cd9406220f55f6fa07be78535744f8) wich uses a projection matrix...

All in all, few more days and I finish off this one.

**Comment by zen3ger** [comment]
Done, I guess. Let me know if I should fixup something.

**Comment by nical** [comment]
Sweet! Thanks a lot!

**Pull request merged**
