### PR TITLE
Fix panic when feeding SVG false arc command

### PR DESCRIPTION
**Pull request by tronical**
When loading an SVG with a path command where an arc has its destination
at the current position and the radii are very small, the SVG spec says
to render it as a line_to segment. This patch calls line_to in that
case, instead of causing a run-time panic.

This helps with sixtyfpsui/sixtyfps#266

### CODE REVIEW

**Comment by nical** [comment]
Thanks!

**Comment by tronical** [comment]
Thanks for the quick review & merge. Just curious: what git branch/tag do you make maintenance releases off of?

Asking because I’d like to crates-patch a git sha1 into our repo (until the next release).

**Comment by nical** [comment]
I don't tag releases on github. Work gets merged in the master branch and if the branch contains unreleased API breaking changes I usually have another branch named after the previous release  where I backport and publish fixes (that's rather rare).

Usually I publish bug fixes on crates.io immediately after merging them. I was busy yesterday unfortunately so that got delayed but I just published `lyon_path 0.17.4`.
When these delays happen don't hesitate to ping me. I'd rather make sure people can work entirely with crates.io unless they want to try out an experimental rewrite that isn't ready yet or things like that.

**Comment by tronical** [comment]
Wonderful. Thanks for the explanation and the frequent releases :)

**Pull request merged**
