### PR TITLE
Bumped up wgpu_svg complexity limit to 16384 from 512

### PR DESCRIPTION
**Pull request by simbleau**
Now using storage buffers instead of uniforms with limit 16384.

### CODE REVIEW

**Comment by simbleau** [comment]
Working on it. Sorry for the delay friend.

**Comment by simbleau** [comment]
Changes now ready for review.

**Comment by simbleau** [comment]
The last commit is just because I felt like it would help and didn't want to make a new PR. There's a new macro which reduces 4 lines to import a WGSL shader to one line. ;-)

**Comment by nical** [comment]
Thanks!

**Pull request merged**
