### PR TITLE
Add PathMeasure.

### PR DESCRIPTION
**Pull request by Mivik**
Implementation mentioned in #787, with tests and simple documents.

### CODE REVIEW

**Comment by nical** [comment]
That was fast! I'll have look soon.

**Comment by nical** [comment]
Nice work! There's one issue with this PR, though: once the edge has been selected, the `t` value along that edge is approximated by a simple linear interpolation. this works for curves with very small curvatures but the larger the curvature the more imprecise the result is and it can make a pretty big difference.

For example replace the content of `examples/wgpu/src/main.rs` with this https://gist.github.com/nical/3c46ff27abffd2847b6f42af913ae41c and run the example.
The small arrows use the path walker while the large ones use the path measurer. They should be moving at constant speed because the t values are increasing at constant speed, however in the case of the measurer, arrows slow down a lot where the curvature is strongest.

Skia deals with it by not caching an item per path segment, instead they split the curves into smaller sub-curves that are flat enough for the distortion to not be an issue (you can use the tolerance threshold there).
Another solution could be to keep caching entire path segments but flatten the selected segment on the fly when doing the lookup. (tradeoff memory/speed).

**Comment by Mivik** [comment]
Thanks for pointing it out! It was my overlooking the problem. Though having problems running the example on my linux laptop (error details are given as follow), I'll try to address the problem soon.

```
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[2022-06-21T15:10:26Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
[2022-06-21T15:10:26Z ERROR winit::platform_impl::platform] X11 error: XError {
        description: "BadMatch (invalid parameter attributes)",
        error_code: 8,
        request_code: 149,
        minor_code: 4,
    }
// ...
// [The same message repeating a lot of times]
// ...
thread 'main' panicked at 'Failed to focus input context: XError { description: "BadMatch (invalid parameter attributes)", error_code: 8, request_code: 149, minor_code: 4 }', /home/mivik/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/event_processor.rs:884:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

And sometimes the error varies as well. In another case, the same message repeats just as above, but the program does not crash immediately. Instead, a black window is shown and `Swap-chain error: Timeout` is repeatedly printed to the console.

This error occurs no matter whether the `examples/wgpu/src/main.rs` is replaced.

**Comment by Mivik** [comment]
Fixed. Now in your example PathMeasure and PathWalker are able to produce the same results.

BTW, in my testing process I noticed a small bug which may cause `PathWalker` to be unable to stop immediately after `Pattern::next` returns `None` so I fixed it.

**Comment by nical** [comment]
Thanks! Looks good to me overall. Please squash this into a single commit, remove test.txt, and I'll merge the PR.
I'll make a few cosmetic changes to the measurer before lyon's next release (nothing big). Also thank you for the walker fix.

**Comment by Mivik** [comment]
Done. So I think I'll close #787 then?

**Comment by nical** [comment]
Woops! A test is failing. I suspect that it is because you now compute the length using only the flattened approximation that is a bit less precise than when approximating the length directly. This shouldn't be a big problem, perhaps the test can be tweaked to use a finer tolerance, the threshold for the assertion be relaxed a bit, or a mix of both.

**Comment by Mivik** [comment]
Strange. All tests have been passed on my laptop. I suspect it has something to do with the floating-point error since I compared them directly in some tests. I'll try to fix it.

**Comment by Mivik** [comment]
OMG. I checked the detail and found that `rustdoc` compiled the example in the document part of `measure.rs`. I never knew that doc-tests even exist and code snippets in document are compiled are executed too, so I just wrote the example without even running it. 😂

**Comment by nical** [comment]
Ah indeed, that one also trips me every now and then. Thanks again!

**Pull request merged**
